### ISSUE TITLE
Travis CI Mac and MIPS builds fail for unmodified master

### ISSUE THREAD

**Issue by jimblandy** [rust-lang-nursery/libc#129] opened 2016-01-03 05:39 UTC
In pull request #128, the Travis CI builds failed in a way that didn't seem to have anything to do with my patch, so I reverted my changes and re-pushed with a tree identical to master. The same builds failed in the same way.

According to the [build results][1], the Mac ARCH=x86_64 build fails with the following message:

> /Users/travis/.cargo/registry/src/github.com-88ac128001ac3a9a/bitflags-0.3.3/src/lib.rs:1:1: 1:1 error: the crate `std` has been compiled with rustc 1.7.0-nightly (d4b67cd7c 2016-01-01), which is incompatible with this version of rustc [E0514]

The Mac ARCH=i686 build fails with the message:

> src/lib.rs:1:1: 1:1 error: the crate `std` has been compiled with rustc 1.7.0-nightly (d4b67cd7c 2016-01-01), which is incompatible with this version of rustc [E0514]

and the TARGET=mips-unknown-linux-gnu build fails with the messages:

> /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '4', this reader only handles version 2 and 3 information.
> /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '0', this reader only handles version 2 and 3 information.
> /home/travis/rust/lib/rustlib/mips-unknown-linux-gnu/lib/liballoc_jemalloc-17a8ccbd.rlib(jemalloc.pic.o): In function `malloc_conf_init':
> /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-linux/build/src/jemalloc/src/jemalloc.c:(.text.malloc_conf_init+0x94): undefined reference to `secure_getenv'
> /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '0', this reader only handles version 2 and 3 information.
> /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '3072', this reader only handles version 2 and 3 information.
> /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-linux/build/src/jemalloc/src/jemalloc.c:(.text.malloc_conf_init+0x98): undefined reference to `secure_getenv'
> collect2: ld returned 1 exit status

after many warnings similar to:

> /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Warning: /home/travis/build/rust-lang-nursery/libc/libc-test/target/mips-unknown-linux-gnu/debug/libc_test uses hard float, /home/travis/rust/lib/rustlib/mips-unknown-linux-gnu/lib/libcompiler-rt.a(mulodi4.o) uses soft float

[1]: https://travis-ci.org/rust-lang-nursery/libc/builds/99911462

**Comment by alexcrichton** [comment] 2016-01-10 22:58
Indeed! This'll be fixed by https://github.com/rust-lang-nursery/libc/pull/114 and is basically a dupe of https://github.com/rust-lang-nursery/libc/issues/100, so I'm gonna close in favor of that. Should be handled soon though!

**Closed by alexcrichton** 2016-01-10 22:58 UTC
